name: Page Deploy
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: yarn
      - run: yarn build
      - name: init repo
        working-directory: ./dist
        run: |
          git init
          git config --local user.email "101846044+FoxstackDeploymentBotPage@users.noreply.github.com"
          git config --local user.name "FoxstackDeploymentBotPage"
          echo "foxstack.tech" > CNAME
          git add . && git commit -m "Update." -a
      - name: push~
        uses: FoxstackClub/github-push-action@master
        with:
          directory: dist
          repository: FoxstackClub/Site.io
          github_token: ${{ secrets.DEPLOY_PAT }}
          force: true
          actor: FoxstackDeploymentBotPage